@extends('layouts.default')
@section('title', 'Terms of Service')
@section('content')
<div class="container">
    <div class="row">
        <div class="col s12">
            <h3>Terms &amp; Conditions</h3>
            <p><b>Acceptance of the Terms of Use.</b> These terms of use are entered into by and between You and SBS Consulting, LLC, an Arizona limited liability company (“Company”, “we” or “us”). The following terms and conditions (these “Terms of Use”), govern your access to and use of http://sportsbusiness.solutions, including any content, functionality, and services offered on or through www.sportsbusiness.solutions (the “Website”).</p>
            <p>Please read the Terms of Use carefully before you start to use the Website. By using the Website you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy, found at <a href="/privacy-policy">SBS Consulting Privacy Policy</a> incorporated herein by reference. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the Website.</p>
            <p>This Website is offered and available to users who are 13 years of age or older. If you do not meet this requirement, you must not access or use the Website. This Website is controlled and operated by the Company from its offices in the United States. We make no representation that materials in the Website are appropriate or available for use in other locations, and access to them from territories where its contents are illegal, is prohibited. Those who choose to access this Website from locations outside the United States are responsible for compliance with all applicable laws.</p>
            <p><b>Changes to the Terms of Use.</b> We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Website thereafter.  Your continued use of the Website following the posting of revised Terms of Use means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>
            <p><b>Accessing the Website and Account Security.</b> We reserve the right to withdraw or amend this Website, and any service or material we provide on the Website, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Website, or the entire Website.</p>
            <p>To access the Website or some of the resources it offers, you may be asked to provide certain personal information, such as a username. You agree that all information you provide to register with this Website or otherwise, including but not limited to through the use of any interactive features on the Website, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
            <p>We have the right to disable any user name, password, or other identifier, whether chosen by you or provided by us, at any time if, in our opinion, you have violated any provision of these Terms of Use.</p>
            <p><b>Intellectual Property Rights.</b> The Website and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof), are owned by the Company, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
            <p>These Terms of Use permit you to use the Website for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website, except as follows:</p>
            <ul class="browser-default">
                <li><p>Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.</p></li>
                <li><p>You may store files that are automatically cached by your Web browser for display enhancement purposes.</p></li>
                <li><p>You may print or download from the Website for your own personal, non-commercial use and not for further reproduction, publication, or distribution.</p></li>
            </ul>
            <p>You must not:</p>
            <ul class="browser-default">
                <li><p>Modify copies of any materials from this site.</p></li>
                <li><p>Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site.</p></li>
            </ul>
            <p>You must not access or use for any commercial purposes any part of the Website or any services or materials available through the Website. No right, title, or interest in or to the Website or any content on the Website is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Website not expressly permitted by these Terms of Use is a breach of these Terms of Use and may violate copyright, trademark, and other laws.</p>
            <p><b>Prohibited Uses.</b> You may use the Website only for lawful purposes and in accordance with these Terms of Use. You agree not to use the Website:</p>
            <ul class="browser-default">
                <li><p>In any way that violates any applicable federal, state, local, or international law or regulation.</p></li>
                <li><p>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</p></li>
                <li><p>To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing).</p></li>
                <li><p>To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Website, or which, as determined by us, may harm the Company or users of the Website or expose them to liability.</p></li>
            </ul>
            <p>Additionally, you agree not to:</p>
            <ul class="browser-default">
                <li><p>Use the Website in any manner that could disable, overburden, damage, or impair the site or interfere with any other party’s use of the Website, including their ability to engage in real time activities through the Website.</p></li>
                <li><p>Use any robot, spider, or other automatic device, process, or means to access the Website for any purpose, including monitoring or copying any of the material on the Website.</p></li>
                <li><p>Use any manual process to monitor or copy any of the material on the Website or for any other unauthorized purpose without our prior written consent.</p></li>
                <li><p>Use any device, software, or routine that interferes with the proper working of the Website.</p></li>
                <li><p>Introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</p></li>
                <li><p>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Website, the server on which the Website is stored, or any server, computer, or database connected to the Website.</p></li>
                <li><p>Attack the Website via a denial-of-service attack or a distributed denial-of-service attack.</p></li>
                <li><p>Otherwise attempt to interfere with the proper working of the Website.</p></li>
            </ul>
            <p><b>User Contributions.</b> The Website may contain message boards, chat rooms, personal web pages or profiles, forums, and other interactive features (collectively, “Interactive Services”) that allow users to post, submit, publish, display, or transmit to other users or other persons (hereinafter, “post”) content or materials (collectively, “User Contributions”) on or through the Website. Any User Contribution you post to the site will be considered non-confidential and non-proprietary. By providing any User Contribution on the Website, you grant us the right to use, reproduce, modify, perform, display, distribute, and otherwise disclose to third parties any such material for any purpose.</p>
            <p>You understand and acknowledge that you are responsible for any User Contributions you submit or contribute, and you, not the Company, have fully responsibility for such content, including its legality, reliability, accuracy, and appropriateness. We are not responsible or liable to any third party for the content or accuracy of any User Contributions posted by you or any other user of the Website.</p>
            <p><b>Monitoring and Enforcement; Termination.</b> We have the right to:</p>
            <ul class="browser-default">
                <li><p>Remove or refuse to post any User Contributions for any or no reason in our sole discretion.</p></li>
                <li><p>Take any action with respect to any User Contribution that we deem necessary or appropriate in our sole discretion, including if we believe that such User Contribution violates the Terms of Use, or could create liability for the Company.</p></li>
                <li><p>Disclose your identity or other information about you to any third party who claims that material posted by you violates their rights, including their intellectual property rights or their right to privacy.</p></li>
                <li><p>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Website.</p></li>
                <li><p>Terminate or suspend your access to all or part of the Website for any violation of these Terms of Use.</p></li>
            </ul>
            <p>Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Website.</p>
            <p>However, we do not undertake to review material before it is posted on the Website, and cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications, or content provided by any user or third party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section.</p>
            <p><b>Reliance on Information Posted.</b> The information presented on or through the Website is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Website, or by anyone who may be informed of any of its contents.</p>
            <p><b>Changes to the Website.</b> We may update the content on this Website from time to time, but its content is not necessarily complete or up-to-date. Any of the material on the Website may be out of date at any given time, and we are under no obligation to update such material.</p>
            <p><b>Information About You and Your Visits to the Website.</b> All information we collect on this Website is subject to our Privacy Policy. By using the Website, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</p>
            <p><b>Linking to the Website and Social Media Features.</b> You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part without our express written consent.</p>
            <p>You agree to cooperate with us in causing any unauthorized framing or linking immediately to stop. We reserve the right to withdraw linking permission without notice. We may disable all or any social media features and any links at any time without notice in our discretion.</p>
            <p><b>Links from the Website.</b> If the Website contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to this Website, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</p>
            <p><b>Disclaimer of Warranties.</b> You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Website will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures for anti-virus protection, and for maintaining a means external to our site for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT.</p>
            <p>YOUR USE OF THE WEBSITE, ITS CONTENT, AND ANY SERVICES OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE COMPANY NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE WEBSITE. WITHOUT LIMITING THE FOREGOING, NEITHER THE COMPANY NOR ANYONE ASSOCIATED WITH THE COMPANY REPRESENTS OR WARRANTS THAT THE WEBSITE, ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</p>
            <p>TO THE FULLEST EXTENT PROVIDED BY LAW, THE COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <p><b>Limitation on Liability.</b> TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL THE COMPANY, OR ITS SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR MANAGERS OR MEMBERS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEBSITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE WEBSITE OR SUCH OTHER WEBSITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE. THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
            <p><b>Indemnification.</b> You agree to defend, indemnify, and hold harmless the Company, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to your violation of these Terms of Use or your use of the Website, including, but not limited to, your User Contributions, any use of the Website’s content, services, and products other than as expressly authorized in these Terms of Use or your use of any information obtained from the Website.</p>
            <p><b>Governing Law and Jurisdiction.</b> All matters relating to the Website and these Terms of Use and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of Arizona without giving effect to any choice or conflict of law provision or rule (whether of the State of Arizona or any other jurisdiction).</p>
            <p><b>Waiver and Severability.</b> No waiver of by the Company of any term or condition set out in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision. If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.</p>
        </div>
    </div>
</div>
@endsection
